### ISSUE TITLE
Progress tracking

### ISSUE THREAD

**Issue by dasvas** [WomenPlusPlus/deploy-impact-23-kpi-3#67]
As an economist, I can see KPI progress against an annual target in the application. This allows me to quickly see if it is on track and if there are any discrepancies in the reporting.

Acceptance criteria:

- [ ] The economist KPI table includes a "Progress" column.
- [ ] The Progress column contains a progress chart for each displayed KPI.
- [ ] The chart shows the percentage of the annual target achieved to date where it makes sense (TBD with Marin).
- [ ] The economist reporting form contains a bullet chart that shows the percentage of the annual target achieved to date (TBD with Marin).

**Comment by maalej** [comment]
Bianca has already created a simple Barchat and Line chart. She need to add a second line showing the target value.
Seen with Marin, she is working on the sql query and Daria is already used to expose endpoints.

**Comment by dasvas** [comment]
The above comment of maalej is incorrect, it is related to a different chart.

**Comment by maalej** [comment]
the progress bar component is ready but need data from backend
